[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wordle_solver"
version = "0.0.1"
requires-python = ">=3.12"

[project.scripts]
solve-wordle = "wordle_solver.main:main"
execute-previous = "wordle_solver.execute_against_previous:main"
